### PR TITLE
 Typos and section on forward referenced fragments

### PR DESCRIPTION
**Pull request by kwk**
I've fixed some typos and added a forward referencing section.

I wasn't sure how a contribution should work here. Do you accept PRs just for the literate program and later generate all the sources? Maybe it makes sense to accept PRs against a special branch from which you then generate the main branch. This way one can have clean PRs with less clutter of generated HTML files for example? Make sense?﻿

### CODE REVIEW

**Comment by jesterKing** [comment]
Please add all generated files along with the PR as well. I'll be checking out the PRs locally and runnig through them anyway. If nothing was tampered with the resulting HTML and code should be the same, in the very least when ignoring whitespace changes.

I would prefer fully typed out words in commit messages, and clean-up the history as much as possible. These three commits could be all collapsed into one.

Other than that the changes look good.

**Comment by kwk** [comment]
@jesterKing will do. I've noticed that literate.html contained changes that I didn't introduce. I've created PR #21 to get those changes in first. They must have slipped through.

**Comment by jesterKing** [comment]
> @jesterKing will do. I've noticed that literate.html contained changes that I didn't introduce. I've created PR #21 to get those changes in first. They must have slipped through.

You're right, they indeed slipped through. I'll land PR #21 in a moment.

**Comment by jesterKing** [comment]
Before you update your PR #19 let me first add a CONTRIBUTORS.md, so that you can add yourself to it with this PR.

**Comment by jesterKing** [comment]
@kwk I have added the CONTRIBUTORS.md file as well now. Please add yourself to it and rebase your changes on main with bb6f722793062116360f197d0c5634a1c0e17981

**Comment by kwk** [comment]
> @kwk I have added the CONTRIBUTORS.md file as well now. Please add yourself to it and rebase your changes on main with [bb6f722](https://github.com/jesterKing/literate/commit/bb6f722793062116360f197d0c5634a1c0e17981)

@jesterKing done.

**Comment by jesterKing** [comment]
Thank you!

**Pull request merged**
